In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
test_data = {
    '订单ID': range(1001, 2001),
    '商品名称': np.random.choice(['手机', '耳机', '卫衣', '水杯'], 1000),
    '销售额': np.round(np.random.uniform(100, 5000, 1000), 2),
    '下单日期': pd.date_range('2024-01-01', periods=1000),
    '城市': np.random.choice(['北京', '上海', '广州', '深圳'], 1000)
}

print(test_data)

{'订单ID': range(1001, 2001), '商品名称': array(['卫衣', '水杯', '手机', '卫衣', '卫衣', '水杯', '手机', '手机', '卫衣', '耳机', '卫衣',
       '卫衣', '卫衣', '卫衣', '水杯', '手机', '水杯', '水杯', '水杯', '卫衣', '耳机', '手机',
       '耳机', '水杯', '水杯', '耳机', '耳机', '耳机', '水杯', '水杯', '手机', '手机', '水杯',
       '耳机', '耳机', '手机', '水杯', '手机', '手机', '卫衣', '卫衣', '卫衣', '耳机', '水杯',
       '水杯', '水杯', '水杯', '卫衣', '耳机', '耳机', '卫衣', '耳机', '卫衣', '水杯', '卫衣',
       '水杯', '水杯', '手机', '卫衣', '手机', '卫衣', '卫衣', '手机', '手机', '卫衣', '耳机',
       '水杯', '手机', '水杯', '耳机', '耳机', '耳机', '手机', '耳机', '手机', '耳机', '水杯',
       '水杯', '卫衣', '水杯', '卫衣', '水杯', '手机', '水杯', '卫衣', '卫衣', '耳机', '手机',
       '水杯', '耳机', '水杯', '水杯', '耳机', '耳机', '耳机', '耳机', '耳机', '水杯', '耳机',
       '手机', '卫衣', '耳机', '耳机', '水杯', '耳机', '耳机', '耳机', '水杯', '耳机', '卫衣',
       '水杯', '卫衣', '水杯', '耳机', '卫衣', '水杯', '手机', '耳机', '水杯', '手机', '水杯',
       '手机', '耳机', '卫衣', '手机', '水杯', '耳机', '手机', '水杯', '水杯', '水杯', '手机',
       '手机', '手机', '卫衣', '手机', '手机', '手机', '卫衣', '手机', '水杯', '手机', '水杯',
       '水杯', '水杯', '卫衣', '卫衣', '卫衣', '手机', '水杯', '卫衣', '卫衣', '手机', '卫衣',
       '手机', '耳机', '卫衣', '耳机', '手机', '水杯', '卫衣', '手机', '水杯', '水杯', '耳机',
       '手机', '水杯', '卫衣', '卫衣', '耳机', '水杯', '手机', '卫衣', '水杯', '水杯', '耳机',
       '卫衣', '卫衣', '手机', '卫衣', '手机', '卫衣', '耳机', '卫衣', '手机', '手机', '耳机',
       '卫衣', '卫衣', '耳机', '卫衣', '卫衣', '手机', '卫衣', '卫衣', '耳机', '耳机', '水杯',
       '手机', '卫衣', '卫衣', '水杯', '卫衣', '手机', '水杯', '手机', '水杯', '水杯', '耳机',
       '手机', '卫衣', '卫衣', '手机', '卫衣', '卫衣', '手机', '水杯', '手机', '水杯', '卫衣',
       '卫衣', '卫衣', '耳机', '水杯', '耳机', '耳机', '手机', '耳机', '手机', '手机', '耳机',
       '水杯', '水杯', '水杯', '水杯', '水杯', '耳机', '耳机', '卫衣', '水杯', '耳机', '卫衣',
       '水杯', '手机', '卫衣', '耳机', '手机', '手机', '手机', '卫衣', '耳机', '手机', '水杯',
       '手机', '手机', '卫衣', '卫衣', '耳机', '水杯', '卫衣', '手机', '耳机', '手机', '手机',
       '卫衣', '耳机', '水杯', '水杯', '卫衣', '卫衣', '耳机', '水杯', '水杯', '水杯', '手机',
       '水杯', '手机', '耳机', '手机', '耳机', '水杯', '水杯', '耳机', '卫衣', '耳机', '卫衣',
       '手机', '手机', '手机', '水杯', '手机', '卫衣', '手机', '耳机', '耳机', '水杯', '耳机',
       '卫衣', '手机', '水杯', '手机', '手机', '卫衣', '耳机', '耳机', '手机', '水杯', '耳机',
       '水杯', '耳机', '水杯', '卫衣', '水杯', '卫衣', '卫衣', '水杯', '卫衣', '手机', '卫衣',
       '耳机', '水杯', '手机', '水杯', '耳机', '耳机', '耳机', '卫衣', '卫衣', '水杯', '水杯',
       '手机', '手机', '水杯', '卫衣', '耳机', '水杯', '手机', '卫衣', '水杯', '水杯', '卫衣',
       '水杯', '卫衣', '耳机', '卫衣', '卫衣', '卫衣', '水杯', '水杯', '卫衣', '水杯', '手机',
       '手机', '水杯', '水杯', '卫衣', '耳机', '水杯', '手机', '卫衣', '水杯', '手机', '手机',
       '耳机', '卫衣', '卫衣', '耳机', '耳机', '卫衣', '卫衣', '水杯', '水杯', '耳机', '水杯',
       '手机', '水杯', '水杯', '手机', '耳机', '手机', '水杯', '耳机', '水杯', '手机', '手机',
       '水杯', '卫衣', '卫衣', '手机', '手机', '卫衣', '卫衣', '水杯', '水杯', '卫衣', '水杯',
       '水杯', '耳机', '水杯', '手机', '水杯', '水杯', '卫衣', '手机', '水杯', '水杯', '耳机',
       '水杯', '水杯', '耳机', '卫衣', '水杯', '耳机', '手机', '卫衣', '手机', '手机', '耳机',
       '水杯', '耳机', '耳机', '耳机', '耳机', '卫衣', '水杯', '手机', '手机', '水杯', '手机',
       '水杯', '手机', '耳机', '手机', '水杯', '水杯', '水杯', '水杯', '水杯', '卫衣', '卫衣',
       '手机', '水杯', '手机', '水杯', '水杯', '卫衣', '卫衣', '耳机', '卫衣', '耳机', '耳机',
       '耳机', '耳机', '耳机', '手机', '卫衣', '耳机', '水杯', '卫衣', '卫衣', '耳机', '手机',
       '耳机', '手机', '水杯', '卫衣', '水杯', '手机', '手机', '水杯', '手机', '水杯', '卫衣',
       '水杯', '卫衣', '水杯', '手机', '水杯', '手机', '水杯', '水杯', '耳机', '手机', '耳机',
       '手机', '耳机', '卫衣', '水杯', '手机', '手机', '水杯', '手机', '手机', '耳机', '手机',
       '卫衣', '卫衣', '水杯', '手机', '水杯', '卫衣', '手机', '手机', '水杯', '卫衣', '手机',
       '水杯', '卫衣', '水杯', '耳机', '手机', '耳机', '卫衣', '耳机', '耳机', '卫衣', '水杯',
       '耳机', '水杯', '耳机', '水杯', '卫衣', '耳机', '卫衣', '耳机', '卫衣', '卫衣', '耳机',
       '耳机', '耳机', '手机', '水杯', '手机', '手机', '卫衣', '耳机', '水杯', '卫衣', '手机',
       '耳机', '卫衣', '耳机', '卫衣', '耳机', '手机', '水杯', '手机', '水杯', '耳机', '卫衣',
       '手机', '水杯', '手机', '水杯', '手机', '水杯', '水杯', '耳机', '水杯', '耳机', '水杯',
       '卫衣', '卫衣', '卫衣', '水杯', '耳机', '耳机', '水杯', '卫衣', '卫衣', '耳机', '卫衣',
       '手机', '耳机', '卫衣', '耳机', '手机', '耳机', '耳机', '耳机', '耳机', '手机', '水杯',
       '耳机', '耳机', '卫衣', '耳机', '卫衣', '水杯', '手机', '手机', '水杯', '手机', '水杯',
       '水杯', '水杯', '手机', '卫衣', '水杯', '耳机', '手机', '水杯', '水杯', '耳机', '卫衣',
       '卫衣', '卫衣', '水杯', '水杯', '水杯', '手机', '耳机', '水杯', '耳机', '耳机', '卫衣',
       '手机', '水杯', '卫衣', '卫衣', '水杯', '耳机', '卫衣', '耳机', '手机', '耳机', '手机',
       '耳机', '卫衣', '卫衣', '手机', '水杯', '手机', '手机', '耳机', '耳机', '手机', '卫衣',
       '耳机', '水杯', '耳机', '耳机', '水杯', '手机', '水杯', '手机', '手机', '手机', '水杯',
       '手机', '卫衣', '水杯', '卫衣', '手机', '耳机', '手机', '卫衣', '卫衣', '水杯', '耳机',
       '水杯', '卫衣', '手机', '耳机', '手机', '手机', '耳机', '水杯', '手机', '卫衣', '手机',
       '耳机', '耳机', '耳机', '水杯', '手机', '水杯', '水杯', '耳机', '耳机', '水杯', '手机',
       '卫衣', '水杯', '手机', '耳机', '耳机', '手机', '卫衣', '耳机', '耳机', '耳机', '手机',
       '水杯', '耳机', '水杯', '卫衣', '耳机', '耳机', '卫衣', '耳机', '水杯', '手机', '水杯',
       '手机', '手机', '水杯', '水杯', '水杯', '水杯', '卫衣', '耳机', '手机', '水杯', '水杯',
       '水杯', '卫衣', '水杯', '水杯', '水杯', '耳机', '卫衣', '水杯', '手机', '手机', '手机',
       '卫衣', '卫衣', '手机', '水杯', '卫衣', '手机', '手机', '水杯', '耳机', '卫衣', '水杯',
       '手机', '手机', '水杯', '卫衣', '耳机', '耳机', '手机', '卫衣', '耳机', '卫衣', '卫衣',
       '手机', '耳机', '水杯', '手机', '耳机', '耳机', '耳机', '耳机', '耳机', '卫衣', '手机',
       '卫衣', '水杯', '耳机', '手机', '耳机', '手机', '卫衣', '手机', '水杯', '水杯', '手机',
       '手机', '手机', '手机', '水杯', '耳机', '手机', '手机', '水杯', '水杯', '卫衣', '手机',
       '卫衣', '水杯', '水杯', '耳机', '手机', '卫衣', '水杯', '水杯', '卫衣', '耳机', '水杯',
       '手机', '水杯', '手机', '卫衣', '手机', '卫衣', '手机', '卫衣', '手机', '耳机', '手机',
       '手机', '耳机', '水杯', '水杯', '手机', '耳机', '手机', '卫衣', '卫衣', '手机', '水杯',
       '水杯', '手机', '手机', '卫衣', '水杯', '手机', '卫衣', '水杯', '耳机', '卫衣', '水杯',
       '水杯', '卫衣', '耳机', '卫衣', '水杯', '手机', '手机', '卫衣', '水杯', '手机', '水杯',
       '卫衣', '手机', '水杯', '手机', '卫衣', '水杯', '手机', '卫衣', '手机', '手机', '耳机',
       '耳机', '卫衣', '耳机', '卫衣', '耳机', '手机', '卫衣', '卫衣', '手机', '卫衣', '卫衣',
       '耳机', '卫衣', '水杯', '手机', '耳机', '耳机', '水杯', '手机', '手机', '耳机', '卫衣',
       '耳机', '手机', '水杯', '耳机', '手机', '耳机', '卫衣', '耳机', '耳机', '手机', '手机',
       '手机', '耳机', '卫衣', '水杯', '水杯', '手机', '手机', '耳机', '水杯', '手机', '卫衣',
       '卫衣', '手机', '手机', '水杯', '水杯', '耳机', '水杯', '卫衣', '卫衣', '手机', '水杯',
       '耳机', '卫衣', '卫衣', '耳机', '耳机', '卫衣', '卫衣', '耳机', '卫衣', '手机', '手机',
       '耳机', '水杯', '耳机', '耳机', '水杯', '水杯', '水杯', '手机', '卫衣', '手机', '卫衣',
       '手机', '卫衣', '手机', '水杯', '耳机', '手机', '卫衣', '水杯', '手机', '手机', '水杯',
       '手机', '耳机', '手机', '耳机', '耳机', '水杯', '手机', '水杯', '手机', '手机', '卫衣',
       '手机', '水杯', '耳机', '手机', '卫衣', '水杯', '手机', '水杯', '卫衣', '卫衣', '水杯',
       '手机', '耳机', '卫衣', '手机', '手机', '耳机', '卫衣', '卫衣', '手机', '手机', '耳机',
       '耳机', '卫衣', '水杯', '卫衣', '手机', '卫衣', '水杯', '耳机', '水杯', '水杯', '水杯',
       '耳机', '水杯', '水杯', '水杯', '手机', '水杯', '耳机', '水杯', '水杯', '耳机', '水杯',
       '耳机', '水杯', '耳机', '水杯', '水杯', '手机', '手机', '水杯', '水杯', '卫衣'],
      dtype='<U2'), '销售额': array([3520.99, 2726.87, 1616.69, 4087.6 , 3455.18,  896.82, 4563.54,
       4130.43, 4754.02, 3656.03, 3105.73, 2149.39, 4670.37, 4343.71,
        321.57,  229.2 , 1944.67, 4071.71, 4937.65,  837.04, 3011.24,
       1966.37, 4852.58, 4226.38, 4207.81, 2396.6 , 2132.62, 1439.69,
        376.24, 4337.14, 4083.21, 4998.62, 4983.52, 2821.62, 3868.04,
       4729.35, 4263.27, 1312.01, 2307.67,  732.88, 4774.85, 3070.26,
       1220.35, 3391.33, 3128.83, 1855.  ,  656.43, 3390.71, 2649.51,
       3884.36, 2648.8 , 4275.69, 2804.34, 2848.6 , 4395.6 , 2077.07,
        756.67,  241.04, 3800.17, 3139.52, 3549.99, 1143.52,  768.22,
        171.27, 1817.88, 2990.6 , 2022.  , 2243.63, 4530.38, 1806.45,
       2618.55, 3939.9 , 2043.06, 3148.22, 4325.58, 4752.65,  820.66,
       4640.28, 2511.37, 1365.4 , 2349.77, 4902.16, 2513.83, 1710.88,
       3203.66, 1276.71,  471.73,  731.51,  727.42,  844.32,  780.25,
       3240.29,  991.21, 1793.77, 4494.26, 2422.41, 3371.03,  944.37,
       1042.22,  300.26,  927.78, 1465.09,  967.35,  534.64,  691.12,
       2357.82, 1111.04, 1884.92, 2566.74, 3482.93,  292.63, 4017.11,
       3176.71,  500.62, 4380.54, 4612.27,  399.28, 1456.7 , 4050.39,
       3766.47, 1004.15, 1125.81, 1915.31, 2474.16, 3129.45, 1907.68,
       2366.42, 3762.61,  279.75, 1336.94, 3595.41, 4486.51, 2607.22,
       2707.36,  625.14, 2292.32, 2709.82, 1288.11, 1419.29, 1948.69,
        198.35, 1678.19, 1136.1 , 1704.74,  686.83, 4463.58, 3008.6 ,
       3427.6 , 3966.94, 2542.37,  525.91, 2731.82, 2975.52, 3752.65,
       2215.13,  725.14, 1490.5 , 1879.1 , 3264.99, 2896.81, 1844.87,
       4933.92, 3068.3 , 1262.41,  598.73,  849.01, 1305.19,  887.34,
       1014.18, 1496.97,  949.53, 4494.15,  493.15, 2670.11, 2110.94,
       4913.66,  648.99, 2049.49, 4850.41, 4340.98, 4103.65, 1363.72,
        937.35, 3376.35, 4653.94, 2828.14, 2900.9 , 1471.9 , 3870.52,
       1016.51, 1686.03, 2184.64, 2587.29, 1287.81,  662.7 , 3092.04,
       1514.29, 2948.07,  856.38, 2457.59, 2709.69,  353.94, 1749.36,
        758.63,  410.54, 4950.81, 1679.53, 4068.38, 1347.74, 3439.36,
       3825.12, 3018.63, 2410.72, 2118.02, 1809.45, 4654.69, 4170.04,
       4828.63,  709.06, 3681.25, 4697.87,  988.04,  425.83, 3731.49,
       2914.92, 4224.96,  784.88, 3996.81, 1087.97,  901.91,  904.9 ,
       4091.42, 3359.47, 2663.02, 1858.27, 4398.28, 2022.98, 4101.34,
       2251.76, 1947.03, 2367.13, 1576.75, 3763.29, 2563.33, 1237.84,
       4507.92, 1981.07, 2763.41, 4541.71, 3158.77,  672.8 , 4705.18,
       3175.77, 1741.04,  782.43, 3990.72, 3138.36, 2713.96, 4480.07,
       3964.13,  843.21, 1627.44, 1317.6 , 3745.34,  264.31, 2892.46,
       3836.05, 4396.15, 1776.2 , 4124.16,  642.1 , 4247.62,  724.69,
       2046.71, 4006.75,  834.6 , 1223.33, 3639.04, 3628.18, 3241.62,
       3500.35, 2759.35, 1333.82, 1793.91,  989.83, 4551.41, 2958.62,
       2064.17, 2363.83, 4741.69,  851.42, 2972.53, 2578.85, 3096.13,
        188.74, 4373.41, 4667.38, 2869.15, 3513.59, 4620.25, 3565.47,
        847.44, 2923.81, 3072.9 , 2178.24, 3708.58, 4678.4 , 4635.29,
       2309.11,  654.87, 4925.72, 4210.6 ,  710.85, 4612.13, 4362.49,
       2642.31, 2997.25, 2055.11,  368.33, 1742.47, 4033.98,  122.7 ,
       1734.15, 2051.03, 2733.24, 4607.29, 1797.1 , 1800.07, 3713.76,
       2315.87, 1200.56, 2316.95,  790.2 ,  964.3 , 2542.  , 2152.73,
       4582.74, 1875.73, 2944.88, 3198.1 ,  164.16, 3351.33,  972.38,
       4809.24,  828.45, 2131.66,  518.21, 4984.68, 2560.76, 3017.39,
        428.67, 3774.81, 1128.54, 4500.47, 1105.18, 1034.37,  279.09,
       2413.13, 2867.72,  421.97, 3900.09, 2321.12, 2669.51, 2259.74,
       2063.74, 2842.24,  860.68,  991.45, 4322.75, 4735.97, 1929.22,
       1426.65, 3255.6 , 2102.8 ,  224.39,  865.15, 3608.26, 3328.73,
        232.77, 1187.66, 1232.27, 3392.27,  196.58,  610.13, 4019.59,
        974.87, 3298.46, 1267.1 ,  587.26, 1291.54, 3639.11, 4292.91,
       4168.08, 2046.2 , 3373.62, 1104.42, 1536.42, 4492.05,  163.71,
        518.99, 1118.64,  230.01,  989.03, 2956.9 , 2164.98, 4474.09,
       4105.47, 1774.91, 1371.17, 1960.49, 2992.45, 1413.51, 3158.33,
       2106.12, 2805.03, 2237.02, 1542.88, 4747.42, 3841.67,  786.55,
       4355.49, 2488.41, 4483.31, 4019.29, 2183.55,  210.1 , 1416.52,
       2754.01, 3204.04, 1363.65,  782.84, 4191.16, 4923.57, 2675.88,
        941.23, 1434.31,  190.11, 4580.06,  676.98, 2924.93, 1442.87,
       2815.47, 3291.96, 4165.73, 1111.46,  153.88,  770.74, 4510.09,
       4382.06, 3027.32, 3042.53, 3358.68,  959.32, 4580.62, 2151.98,
       1977.38, 2642.7 ,  330.13,  914.79, 3716.36,  505.71, 3055.45,
       1302.21, 2007.55, 1514.6 , 1842.8 , 3623.32, 1555.9 , 2875.38,
       2432.65, 3351.99, 4690.47, 3689.6 , 1153.21,  252.8 , 1385.09,
       3015.88,  351.99, 2532.19, 3024.53, 1737.8 , 3877.47,  622.33,
        468.18, 3668.12, 2527.91, 3473.17, 2230.65, 1307.37, 4113.6 ,
       4017.14, 3504.01, 1433.51, 2992.13, 1868.77,  548.75, 4594.84,
        770.41, 4756.16, 2285.43, 1007.15, 2755.31, 4377.43, 3687.9 ,
       4052.15, 3328.04, 3492.16, 4261.06, 1323.37, 2498.18, 1183.93,
       4939.57, 4725.89,  293.19, 3557.32, 4633.72,  984.82, 2882.93,
       4585.89,  266.34, 3517.36, 1557.01, 4629.54, 4858.19, 4726.91,
       2423.65, 4324.01, 4238.29, 1663.59, 4161.69,  281.34, 3021.72,
       1227.04,  690.78,  477.07, 3511.82, 1765.39, 3651.36,  420.25,
       1644.92, 2743.51, 3974.54, 1661.89, 3166.87, 4441.29, 3117.73,
       1241.5 ,  219.56, 4363.48,  204.22, 4386.04, 2691.79, 4701.43,
       4014.04, 4989.88, 1818.49, 3859.22, 2069.46, 2451.39, 3174.78,
       4381.02, 4922.01, 3864.54, 2147.06, 2164.65, 3714.15, 1270.01,
        641.32, 1837.65, 1507.47, 1551.91, 1244.68,  306.26,  187.58,
       4939.84, 2196.09, 1983.2 , 3430.27, 1169.44, 4754.81, 3953.09,
        538.11, 2146.15, 4407.68, 4729.19, 2390.27, 3105.72,  918.47,
       4956.73, 1235.19, 4719.39, 3283.27, 3077.91, 2612.17, 1230.28,
        964.99, 1180.38, 1013.55, 3919.96, 1815.61,  383.43, 4848.6 ,
       4430.55, 4645.99, 4975.05,  952.09, 2041.59, 3815.37, 3510.5 ,
        854.09, 4097.58, 1199.76, 1196.71, 2731.17, 3005.41, 2942.42,
        548.29, 4399.56, 1401.44,  734.62, 4454.87, 4782.69, 4324.43,
       4066.63, 3310.69, 2799.2 ,  526.24, 2101.42, 1926.17, 1372.79,
       3644.76, 2529.79,  497.13, 1178.9 , 3447.97,  473.04, 4270.91,
       2526.22, 2454.87, 3002.8 , 4140.94, 1804.27, 3422.28, 2872.09,
       1408.44, 4405.29, 4007.39, 3326.41, 4267.85, 4349.74, 3570.98,
       4201.37, 3517.61, 3432.69, 3131.2 , 3788.31,  877.17, 4416.27,
       4372.03,  243.31, 4146.5 ,  731.46, 1742.08, 3743.19,  887.72,
       4108.04, 4177.46, 2586.59,  131.29, 1506.49, 3122.94, 4907.81,
       3195.89, 1373.04, 3206.63, 2745.93, 3921.24,  624.21, 3829.04,
       2752.21, 4818.66, 1775.17, 3199.85, 4666.94,  602.3 , 4692.42,
       3470.64,  432.4 , 1574.72, 3570.04,  430.02, 2952.64, 1794.83,
       3142.49,  324.14, 4370.53, 4870.1 , 4847.5 , 3773.29,  737.42,
       3815.49,  220.48,  208.41, 1685.69, 2494.35, 3875.  , 3448.15,
       2284.92, 1440.77, 4985.91, 2188.29, 2311.8 ,  901.76, 3994.57,
       3499.04, 1181.77,  503.67, 3434.45, 3307.1 , 1438.97, 4759.23,
        840.18, 2218.44, 4723.72, 2156.66, 3228.78, 2048.21, 1443.65,
       4921.49, 2105.74, 4481.09, 1226.78, 1144.21,  252.56, 3293.17,
       1905.78, 4335.36, 2418.73, 4844.15, 1009.08, 4356.25, 3905.32,
       3877.52, 4239.44, 3829.02, 3168.48,  743.1 ,  259.38, 4612.15,
       3121.59, 4003.03, 2459.46,  674.81,  713.41, 3459.27, 2208.5 ,
       1082.57, 2508.81,  414.62, 2951.66, 1418.07, 4008.04, 1620.77,
       2330.58,  156.94,  454.99, 2023.22, 2451.7 , 3040.1 , 1529.15,
       3505.41, 4314.6 , 3921.27,  294.13, 2454.48,  614.16, 1286.02,
       4934.65,  798.23, 2544.55, 3128.96, 3542.08, 2842.28,  147.88,
       1699.66, 2636.79,  530.55, 1818.07,  262.7 ,  485.03, 2044.92,
        750.31, 2880.95, 3478.38, 4022.87, 1080.74,  920.66,  612.38,
       3218.51, 3561.73,  254.77, 4687.44,  354.66, 2752.35, 3574.4 ,
       4367.75, 3599.03, 4028.47, 1763.31, 4092.64,  492.56, 4484.6 ,
       2783.2 , 4104.76, 2316.36, 3253.53, 2679.37, 3684.79,  499.99,
        395.73, 1310.81,  881.77, 4371.74, 1174.15, 4881.74, 1750.79,
        992.38, 3969.52, 3327.67, 2541.16, 2821.28, 3624.09, 1219.43,
       4982.04, 4876.49, 3286.6 , 1077.76, 3433.12,  453.77,  250.2 ,
       1362.65, 2366.85, 4354.54, 3663.13, 3739.26, 2184.92, 1795.08,
       1918.09, 4939.48,  296.54, 4348.45, 2935.51, 2249.22, 3653.76,
       2484.68, 4379.77, 4513.44, 2166.43, 1456.46, 3002.52, 4570.58,
       1132.24, 3152.54, 3194.65, 3692.25,  744.68, 3607.54, 4554.26,
        980.45, 1263.96, 4859.84,  986.79, 4286.49, 2512.16, 1311.43,
       4366.67, 2282.  , 2622.61, 1860.24, 3005.46,  901.27, 2016.3 ,
       4850.12, 1364.85, 3318.01, 1693.43, 3890.02,  741.28, 4852.12,
       2323.57, 1256.65,  460.13,  931.81, 2646.89, 1751.32, 4161.53,
       2211.35, 1318.7 , 3124.01, 3563.21,  918.51,  921.33,  279.69,
       3708.37, 3352.64, 2425.69, 4236.44, 4047.78, 2968.24, 4354.53,
       1108.62,  648.41, 1421.77,  379.73, 2702.73, 4689.37,  292.78,
        698.34, 2315.78, 4675.99, 1649.16, 2585.45,  303.71,  826.88,
       4934.49, 4829.08,  124.21, 4763.88, 3231.69, 4352.8 , 2328.23,
       2626.42, 2495.35, 3367.63,  784.29,  246.87, 1608.86, 3552.94,
       1089.08, 3399.82, 4852.57,  560.11, 3395.75, 2274.38, 4353.9 ,
        968.03, 3493.87, 4206.76, 4728.61, 3447.92, 2536.16, 3127.45,
       4357.63, 2895.99,  248.9 , 4661.65, 3478.68, 3414.92, 1156.81,
       3328.54, 2029.94, 3291.04,  622.31, 3323.44, 4997.13,  336.24,
       4888.15, 2093.85, 4366.69, 3933.69, 2878.38, 3718.4 , 4404.73,
       2080.29, 1702.46, 3371.21, 4058.45, 3835.2 , 4009.29, 2234.36,
       4107.39,  689.02, 2768.  ,  128.22, 1690.47, 1895.66, 2041.25,
       3507.79, 2003.93, 2298.6 , 1263.97, 1928.93, 1213.62,  458.66,
       3056.9 , 3374.24, 3135.5 , 2371.12, 1960.95, 4330.33]), '下单日期': DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2026-09-17', '2026-09-18', '2026-09-19', '2026-09-20',
               '2026-09-21', '2026-09-22', '2026-09-23', '2026-09-24',
               '2026-09-25', '2026-09-26'],
              dtype='datetime64[us]', length=1000, freq='D'), '城市': array(['深圳', '上海', '上海', '深圳', '北京', '北京', '上海', '北京', '深圳', '北京', '上海',
       '深圳', '北京', '广州', '深圳', '深圳', '广州', '广州', '深圳', '广州', '上海', '上海',
       '上海', '深圳', '广州', '广州', '北京', '北京', '广州', '广州', '广州', '深圳', '广州',
       '北京', '深圳', '广州', '北京', '深圳', '广州', '广州', '广州', '深圳', '北京', '北京',
       '上海', '广州', '上海', '上海', '北京', '深圳', '深圳', '北京', '深圳', '上海', '广州',
       '北京', '广州', '深圳', '广州', '深圳', '深圳', '上海', '深圳', '上海', '上海', '上海',
       '北京', '北京', '深圳', '上海', '北京', '上海', '广州', '广州', '广州', '深圳', '上海',
       '广州', '北京', '广州', '广州', '广州', '深圳', '北京', '上海', '北京', '上海', '深圳',
       '深圳', '深圳', '深圳', '上海', '广州', '上海', '北京', '深圳', '深圳', '北京', '上海',
       '广州', '广州', '北京', '广州', '上海', '上海', '北京', '上海', '深圳', '北京', '上海',
       '北京', '广州', '上海', '深圳', '上海', '北京', '北京', '上海', '深圳', '深圳', '深圳',
       '北京', '上海', '广州', '北京', '深圳', '上海', '深圳', '广州', '深圳', '深圳', '广州',
       '上海', '北京', '上海', '广州', '深圳', '上海', '北京', '广州', '上海', '北京', '广州',
       '北京', '广州', '深圳', '上海', '北京', '广州', '北京', '北京', '上海', '深圳', '北京',
       '广州', '广州', '深圳', '广州', '深圳', '广州', '上海', '北京', '上海', '北京', '北京',
       '北京', '上海', '北京', '上海', '深圳', '广州', '广州', '北京', '上海', '广州', '上海',
       '上海', '北京', '广州', '北京', '北京', '广州', '广州', '深圳', '深圳', '上海', '广州',
       '深圳', '上海', '上海', '上海', '深圳', '广州', '北京', '上海', '深圳', '深圳', '北京',
       '北京', '深圳', '广州', '北京', '深圳', '北京', '广州', '上海', '北京', '广州', '深圳',
       '北京', '北京', '深圳', '上海', '深圳', '北京', '深圳', '广州', '深圳', '北京', '深圳',
       '上海', '深圳', '上海', '广州', '上海', '深圳', '北京', '上海', '广州', '上海', '上海',
       '上海', '广州', '深圳', '上海', '上海', '北京', '广州', '上海', '广州', '上海', '深圳',
       '深圳', '上海', '深圳', '上海', '深圳', '北京', '北京', '北京', '广州', '广州', '北京',
       '广州', '深圳', '上海', '上海', '上海', '北京', '广州', '深圳', '深圳', '北京', '深圳',
       '深圳', '深圳', '深圳', '广州', '深圳', '上海', '北京', '广州', '深圳', '广州', '深圳',
       '上海', '北京', '深圳', '深圳', '深圳', '深圳', '北京', '北京', '上海', '北京', '深圳',
       '上海', '上海', '上海', '深圳', '广州', '深圳', '北京', '北京', '深圳', '深圳', '上海',
       '深圳', '上海', '北京', '上海', '深圳', '北京', '广州', '上海', '北京', '上海', '北京',
       '北京', '上海', '广州', '北京', '北京', '北京', '广州', '广州', '深圳', '上海', '广州',
       '上海', '深圳', '上海', '广州', '上海', '广州', '上海', '广州', '广州', '上海', '深圳',
       '北京', '深圳', '上海', '深圳', '广州', '北京', '上海', '上海', '上海', '北京', '广州',
       '上海', '深圳', '上海', '上海', '上海', '上海', '广州', '深圳', '广州', '深圳', '上海',
       '北京', '广州', '北京', '广州', '上海', '广州', '上海', '广州', '上海', '上海', '深圳',
       '上海', '深圳', '上海', '北京', '上海', '北京', '北京', '上海', '北京', '深圳', '广州',
       '上海', '北京', '上海', '深圳', '上海', '上海', '北京', '深圳', '广州', '广州', '北京',
       '上海', '北京', '北京', '北京', '上海', '深圳', '北京', '上海', '深圳', '北京', '广州',
       '深圳', '北京', '深圳', '深圳', '深圳', '深圳', '深圳', '深圳', '北京', '广州', '上海',
       '深圳', '上海', '北京', '深圳', '广州', '上海', '深圳', '北京', '广州', '上海', '上海',

In [3]:
df = pd.DataFrame(test_data)

In [4]:
print(df)

     订单ID 商品名称      销售额       下单日期  城市
0    1001   卫衣  3520.99 2024-01-01  深圳
1    1002   水杯  2726.87 2024-01-02  上海
2    1003   手机  1616.69 2024-01-03  上海
3    1004   卫衣  4087.60 2024-01-04  深圳
4    1005   卫衣  3455.18 2024-01-05  北京
..    ...  ...      ...        ...  ..
995  1996   手机  3374.24 2026-09-22  深圳
996  1997   手机  3135.50 2026-09-23  深圳
997  1998   水杯  2371.12 2026-09-24  上海
998  1999   水杯  1960.95 2026-09-25  上海
999  2000   卫衣  4330.33 2026-09-26  上海

[1000 rows x 5 columns]

In [5]:
df

     订单ID 商品名称      销售额       下单日期  城市
0    1001   卫衣  3520.99 2024-01-01  深圳
1    1002   水杯  2726.87 2024-01-02  上海
2    1003   手机  1616.69 2024-01-03  上海
3    1004   卫衣  4087.60 2024-01-04  深圳
4    1005   卫衣  3455.18 2024-01-05  北京
..    ...  ...      ...        ...  ..
995  1996   手机  3374.24 2026-09-22  深圳
996  1997   手机  3135.50 2026-09-23  深圳
997  1998   水杯  2371.12 2026-09-24  上海
998  1999   水杯  1960.95 2026-09-25  上海
999  2000   卫衣  4330.33 2026-09-26  上海

[1000 rows x 5 columns]

In [6]:
df.to_csv(
    'sales_opt.csv',
    index=False,
    float_format='%.2f',
    encoding='utf-8',
    chunksize=500,
    compression='zip'
)

In [8]:
df_read = pd.read_csv('sales_opt.csv', compression='zip')
df_read

     订单ID 商品名称      销售额        下单日期  城市
0    1001   卫衣  3520.99  2024-01-01  深圳
1    1002   水杯  2726.87  2024-01-02  上海
2    1003   手机  1616.69  2024-01-03  上海
3    1004   卫衣  4087.60  2024-01-04  深圳
4    1005   卫衣  3455.18  2024-01-05  北京
..    ...  ...      ...         ...  ..
995  1996   手机  3374.24  2026-09-22  深圳
996  1997   手机  3135.50  2026-09-23  深圳
997  1998   水杯  2371.12  2026-09-24  上海
998  1999   水杯  1960.95  2026-09-25  上海
999  2000   卫衣  4330.33  2026-09-26  上海

[1000 rows x 5 columns]

In [9]:
df

     订单ID 商品名称      销售额       下单日期  城市
0    1001   卫衣  3520.99 2024-01-01  深圳
1    1002   水杯  2726.87 2024-01-02  上海
2    1003   手机  1616.69 2024-01-03  上海
3    1004   卫衣  4087.60 2024-01-04  深圳
4    1005   卫衣  3455.18 2024-01-05  北京
..    ...  ...      ...        ...  ..
995  1996   手机  3374.24 2026-09-22  深圳
996  1997   手机  3135.50 2026-09-23  深圳
997  1998   水杯  2371.12 2026-09-24  上海
998  1999   水杯  1960.95 2026-09-25  上海
999  2000   卫衣  4330.33 2026-09-26  上海

[1000 rows x 5 columns]

In [13]:
with pd.ExcelWriter('sales_opt.xlsx') as writer:
    df.to_excel(
        writer,
        sheet_name='销售数据',
        index=False,
        merge_cells=False
    )
    df_summary = df.groupby('城市')['销售额'].sum().reset_index()
    df_summary.to_excel(writer, sheet_name='城市汇总', index=False)

print("✅ Excel优化写入完成！")

✅ Excel优化写入完成！

In [15]:
from sqlalchemy import create_engine, INTEGER, FLOAT, DATE

engine = create_engine('sqlite:///pandas_sql')

df.to_sql(
    name='sales_opt',
    con=engine,
    if_exists='append',
    index=False,
    chunksize=100,
    dtype={
        '订单ID': INTEGER,
        '销售额': FLOAT,
        '下单日期': DATE
    }
)

engine.dispose()

In [16]:
df.to_csv(
    'sales_opt_yasuoqian.csv',
    index=False,
    float_format='%.2f',
    encoding='utf-8',
    chunksize=500
)